### ISSUE TITLE
Cannot read property 'add' of undefined

### ISSUE THREAD

**Issue by wyysf** [cheneyweb/parcel-vue#2]
我克隆你的代码，安装之后运行yarn dev 就报错了，具体错误就是“Cannot read property 'add' of undefined”at JSPackager.addAsset (/Users/sunxh/www/parcel_box/parcel-vue/node_modules/parcel-bundler/src/packagers/JSPackager.js:47:32)
    at Bundle._addDeps (/Users/sunxh/www/parcel_box/parcel-vue/node_modules/parcel-bundler/src/Bundle.js:146:20)

**Comment by hanjun126** [comment]
×  Cannot read property 'add' of undefined
    at JSPackager.addAsset (D:\env_web\wamp\www\hxy\node_modules\parcel-bundler\src\packagers\JSPackager.js:53:28)
    at Bundle._addDeps (D:\env_web\wamp\www\hxy\node_modules\parcel-bundler\src\Bundle.js:146:20)
    at <anonymous>

这个错误怎么解决？

**Comment by wacj1425** [comment]
×  Cannot read property 'add' of undefined
    at JSPackager.addAsset (F:\工作目录\本地\parcel-vue\myproject\node_modules\parcel-bundler\src\packagers\JSPackager.js:55:32)
    at Bundle._addDeps (F:\工作目录\本地\parcel-vue\myproject\node_modules\parcel-bundler\src\Bundle.js:208:20)

**Comment by wacj1425** [comment]
好像都是这个问题

**Comment by cheneyweb** [comment]
最新的CLI工具，已经更新至Parcel 1.7.0 版本以上，支持原生VUE构建，不再需要parcel-vue-plugin就可以构建VUE项目，真正零配置
